sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

cache:
  directories:
    - $HOME/.m2

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "yR3V8fQou+INYtMFIaYIq9FXpp+B0jBYdBufarX2X+P6cKtXufsLyrsS3JX2+G7FJSFQlFOFhEJMfHSso5N5p9hALAT4RMxpnOFb6X1bauPsQISjRXItodlj9Akoz81C83UQV9+SL9o/6XHnHcu2SKcZZETYjZgL7Ui0tlQV+5g="
    # AWS_SECRET_ACCESS_KEY
    - secure: "Td60mqV9jZhw/IZo9ST2ynVYeOlVqRK7YZ2IOEFepWa5h9lNv6105Iz9cwCWNIzDu/9dM9locy/E4y5w4o5yShc16X2C0Vkm+0eCDpdpxQ4er8D8I6lTrMFe5IDoFmGJH7NISl60bBl4xu25JiYQc+EFP0uvUQ59/aozn3VrI6o="

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="eperusteet-ylops"

script:
  - mvn clean install -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}

  - mv ${ARTIFACT_NAME}-service/target/${ARTIFACT_NAME}-service.war $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}-service.war
  - mv ${ARTIFACT_NAME}-app/target/${ARTIFACT_NAME}-app.war $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}-app.war
  - cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/
  - cp -vr src/main/resources/tomcat $DOCKER_BUILD_DIR/config/

  - export BASE_IMAGE="baseimage-war:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-war.sh ${ARTIFACT_NAME}

deploy:
  - provider: script
    script: mvn deploy -pl ${ARTIFACT_NAME}-app -DskipTests --settings ci-tools/common/maven-settings.xml
    skip_cleanup: true
    on:
      branch: master

  - provider: script
    script: ./ci-tools/build/upload-image.sh ${ARTIFACT_NAME}
    on:
      all_branches: true
